
# global alias load
source ~/.config/alias/global.alias

autoload -Uz compinit && compinit

# starship prompt configuration
## if the terminal is not linux or xterm,
## then load starship prompt

case "$TERM" in
  linux|xterm) :;;
  *) 
    if type -a starship>/dev/null 2>&1;then;
     prompt off;
     export STARSHIP_CONFIG=~/.config/starship/starship.toml
     eval "$(starship init zsh)";
    else;
      :
    fi;;
esac

# GPG TTY configuration
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye > /dev/null

typeset -U path PATH
setopt hist_ignore_all_dups

