
# global alias load
source ~/.config/alias/global.alias

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

# starship prompt configuration
## if the terminal is not linux or xterm,
## then load starship prompt

case "$TERM" in
  linux|xterm) :;;
  *) 
    if type -a starship>/dev/null 2>&1;then;
     prompt off;
     export STARSHIP_CONFIG=~/.config/starship/starship.toml
     eval "$(starship init zsh)";
    else;
      :
    fi;;
esac

if [[ "$(uname)" == "Darwin" ]];then
  source ~/.config/zsh/zshrc.Darwin
fi

# GPG TTY configuration
if type gpg-connect-agent &>/dev/null; then
  export GPG_TTY=$(tty)
  gpg-connect-agent updatestartuptty /bye > /dev/null
fi

typeset -U path PATH
setopt hist_ignore_all_dups
setopt share_history

function fzf-select-history() {
  FZF_DEFAULT_OPTS='--prompt="History >" --border --padding=1 --margin=1 --no-sort +m --height 80% --reverse --border'
  BUFFER=$(history -n -r 1 | fzf --query "$LBUFFER" --prompt="History >" --border --padding=1 --margin=1 --no-sort +m --height 80% --reverse --border )
  CURSOR=$#BUFFER
  zle redisplay
}
if type -a fzf>/dev/null 2>&1;then;
  zle -N fzf-select-history
  bindkey '^r' fzf-select-history
fi

