
set -g default-terminal 'screen-256color'
set -g terminal-overrides 'xterm:colors=256'

# status bar
# set-option -g status-position top

# Keybindings

set-window-option -g mode-keys vi
set-option -s set-clipboard on

bind-key -n M-Left resize-pane -L 3
bind-key -n M-Right resize-pane -R 3
bind-key -n M-Up resize-pane -U 3
bind-key -n M-Down resize-pane -D 3

# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set-option -g status-justify "left"

# title bar


# status line
# source ~/.config/tmux/statusline.conf
