
# General
command_timeout = 1000

format = """
[](#0b72af)\
$username\
[](bg:#0f4e72 fg:#0b72af)\
$hostname\
[](bg:#444343 fg:#0f4e72)\
$directory\
($git_branch$git_status)\
[ ](#444343)\
"""
#[](fg:#444343 bg:#22a7f2)\
#[](fg:#22a7f2 bg:#444343)\
#[](fg:#22a7f2 bg:#444343)\

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#0b72af"
style_root = "bg:#0b72af fg:#ff0000"
format = '[$user]($style)'
disabled = false

[hostname]
style = "bg:#0f4e72"
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
ssh_symbol = ''

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
fish_style_pwd_dir_length = 2
truncation_length = 1
style = "bg:#444343"
read_only = "󰌾"
read_only_style = "fg:red bg:#444343"
format = "[ $path ]($style)[ $read_only]($read_only_style)"


# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#22a7f2"
format = '[](fg:#22a7f2 bg:#444343)[$symbol $branch]($style)'

[git_status]
style = "bg:#22a7f2"
format = '[$all_status$ahead_behind ]($style)[](fg:#22a7f2 bg:#444343)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
